### ISSUE TITLE
AWS provisioning fails 

### ISSUE THREAD

**Issue by aktarali** [digitalrebar/digitalrebar.github.io#4]
This is the raw output from the AWS configs:
{
  "region": "eu-west-1",
  "vpc_id": "!default",
  "provider": "AWS",
  "access_key_id": "AKIAJ2GHPJD2U2TQA2URZ",
  "secret_access_key": "GQv9WxElTl3QyKNPcZPQK9VjC1nMoVd3qW0wNF3V"
}

The error I am getting doesn't seem to reflect what I have configured. Errors below:
cloudwrap_1 | Registering endpoint {"region"=>"eu-west-1", "vpc_id"=>"!default", "provider"=>"AWS", "access_key_id"=>"AKIAJ2GHPJD2U2TQA2URZ", "secret_access_key"=>"GQv9WxElTl3QyKNPcZPQK9VjC1nMoVd3qW0wNF3V"} using {"admin-0"=>"ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDKQpM/zM47xYL8qR0cBOt0AtTO36W1E3CMxvvl49xYMQpZToBRjPYdcWBF9b3pn4mDerQXon2mR5/qFXk0oMAlQ6h/t/uHDCjrHAYVswyDZaCJPvG1U1tW1TElC001ezGRd+4GiLYlfQfZhqx73TNNjFni/Z2vGcwDuNETRWWE/h4Tf6b6YtRmKBFs3Np2e2SFIMyO1ybTyFWawR1ovmz89d3UeuKbi5dOE3h3xMxAWMW3FmadIbzgdQUAMoXjmCfmM7tRB7I4cdauPi1+FAByR+rJWN0gQpt3uiwIHpqK3/2WwYkThJDk7kRbhZzdtrjtT3X2vEDYsYo4DwsqbN5Z rebar@3fb2f44a5ab4\n", "setup-0"=>"ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC/bk4RoTytlf0vx34+ChqFTCu5a1wgjzJToslFfTXysaqZc+AREB9PAnlchauzNFZlrk2jRPZgfYFno7LoseE4Rltn1RuYLnVkeQpmOLnaGtxKDR/tuDJl4eNG/3OyShw/F+Zl2folWDxzM73ac1Tb9/zcHd3TMi7kZlzMjWi2H+81KWHclrdVFgy1sIDeouxl0b6fs079eMrDrMND/OMUnLgmsab8dDUE1h/Du+cXqmmBRs9w2KrOeUMvUnPZ2ZSyKtTf7Puxuk2wto/v3Db4zN73WtfaEtZLiiETIGBtfQBt+5JUunjq4n+iYdyK2BcZfEo460p4Rs6q7FoaS369 ubuntu@ip-172-31-2-233\n"}
cloudwrap_1 | 
cloudwrap_1 | ==> waiter.log <==
cloudwrap_1 | Finding endpoints of servers to check
cloudwrap_1 | Finding endpoints of servers to check
cloudwrap_1 | Finding endpoints of servers to check
cloudwrap_1 | Finding endpoints of servers to check
cloudwrap_1 | Finding endpoints of servers to check
cloudwrap_1 | Finding endpoints of servers to check
cloudwrap_1 | 
cloudwrap_1 | ==> api.log <==
cloudwrap_1 | Creating node 2
cloudwrap_1 | Exception Create: #<ArgumentError: Missing required arguments: aws_access_key_id, aws_secret_access_key>
cloudwrap_1 | Creating node 3
cloudwrap_1 | Exception Create: #<ArgumentError: Missing required arguments: aws_access_key_id, aws_secret_access_key>

Could it be because of the mismatch in the field names? The names in the raw ouput do not match the error field names?

**Comment by zehicle** [comment]
closing this because it's likely been too long
